name: Build WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Compile C++
        run: |
          em++ game.cpp -O2 \
          -s WASM=1 \
          -s EXPORTED_FUNCTIONS='["_init","_move","_getCell","_shuffle"]' \
          -o game.js
          
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
